// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineMusicLibrary;

#nullable disable

namespace OnlineMusicLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231101190929_AddAlbumHash")]
    partial class AddAlbumHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("OnlineMusicLibrary.Playlist", b =>
                {
                    b.Property<uint>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tracks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("username");

                    b.ToTable("playlists");
                });

            modelBuilder.Entity("OnlineMusicLibrary.Track", b =>
                {
                    b.Property<uint>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("album")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("albumArtist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("albumHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("download")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("listen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lyrics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("username");

                    b.ToTable("tracks");
                });

            modelBuilder.Entity("OnlineMusicLibrary.User", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("username");

                    b.HasIndex("token");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
